# Generated by Django 5.2.3 on 2025-06-26 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GameRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает чек'), ('verified', 'Подтверждено'), ('expired', 'Просрочено')], default='pending', max_length=20)),
                ('receipt_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football_app.player')),
            ],
        ),
    ]
