# Generated by Django 5.2.3 on 2025-06-27 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='is_admin',
            new_name='is_registered_for_game',
        ),
    ]
